# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\fubc_lib.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_StackedWidget(object):
    def setupUi(self, StackedWidget):
        StackedWidget.setObjectName("StackedWidget")
        StackedWidget.resize(739, 478)
        StackedWidget.setStyleSheet("Fusion")
        self.LoginPage = QtWidgets.QWidget()
        self.LoginPage.setObjectName("LoginPage")
        self.formLayout = QtWidgets.QFormLayout(self.LoginPage)
        self.formLayout.setContentsMargins(250, 200, -1, -1)
        self.formLayout.setHorizontalSpacing(7)
        self.formLayout.setObjectName("formLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setContentsMargins(0, 0, -1, -1)
        self.gridLayout.setHorizontalSpacing(7)
        self.gridLayout.setObjectName("gridLayout")
        self.user_label = QtWidgets.QLabel(self.LoginPage)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Black")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.user_label.setFont(font)
        self.user_label.setObjectName("user_label")
        self.gridLayout.addWidget(self.user_label, 0, 0, 1, 1)
        self.user_line = QtWidgets.QLineEdit(self.LoginPage)
        self.user_line.setText("")
        self.user_line.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.user_line.setObjectName("user_line")
        self.gridLayout.addWidget(self.user_line, 0, 1, 1, 1)
        self.pass_label = QtWidgets.QLabel(self.LoginPage)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Black")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pass_label.setFont(font)
        self.pass_label.setIndent(12)
        self.pass_label.setOpenExternalLinks(False)
        self.pass_label.setObjectName("pass_label")
        self.gridLayout.addWidget(self.pass_label, 1, 0, 1, 1)
        self.pass_line = QtWidgets.QLineEdit(self.LoginPage)
        self.pass_line.setText("")
        self.pass_line.setEchoMode(QtWidgets.QLineEdit.Password)
        self.pass_line.setObjectName("pass_line")
        self.gridLayout.addWidget(self.pass_line, 1, 1, 1, 1)
        self.loginBtn = QtWidgets.QPushButton(self.LoginPage)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Black")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.loginBtn.setFont(font)
        self.loginBtn.setMouseTracking(False)
        self.loginBtn.setAutoDefault(True)
        self.loginBtn.setObjectName("loginBtn")
        self.gridLayout.addWidget(self.loginBtn, 2, 1, 1, 1)
        self.formLayout.setLayout(0, QtWidgets.QFormLayout.LabelRole, self.gridLayout)
        self.login_error_label = QtWidgets.QLabel(self.LoginPage)
        self.login_error_label.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.login_error_label.setFont(font)
        self.login_error_label.setObjectName("login_error_label")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.login_error_label)
        StackedWidget.addWidget(self.LoginPage)
        self.AddBookPage = QtWidgets.QWidget()
        self.AddBookPage.setObjectName("AddBookPage")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.AddBookPage)
        self.gridLayout_4.setObjectName("gridLayout_4")
        spacerItem = QtWidgets.QSpacerItem(224, 165, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem, 0, 1, 1, 1)
        self.authorBarcodeverticalLayout = QtWidgets.QVBoxLayout()
        self.authorBarcodeverticalLayout.setObjectName("authorBarcodeverticalLayout")
        self.authorGridLayout = QtWidgets.QGridLayout()
        self.authorGridLayout.setObjectName("authorGridLayout")
        self.author_label = QtWidgets.QLabel(self.AddBookPage)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.author_label.setFont(font)
        self.author_label.setObjectName("author_label")
        self.authorGridLayout.addWidget(self.author_label, 0, 0, 1, 1)
        self.last_label = QtWidgets.QLabel(self.AddBookPage)
        self.last_label.setObjectName("last_label")
        self.authorGridLayout.addWidget(self.last_label, 1, 0, 1, 1)
        self.last_name_line = QtWidgets.QLineEdit(self.AddBookPage)
        self.last_name_line.setObjectName("last_name_line")
        self.authorGridLayout.addWidget(self.last_name_line, 1, 1, 1, 1)
        self.first_name_label = QtWidgets.QLabel(self.AddBookPage)
        self.first_name_label.setObjectName("first_name_label")
        self.authorGridLayout.addWidget(self.first_name_label, 2, 0, 1, 1)
        self.first_name_line = QtWidgets.QLineEdit(self.AddBookPage)
        self.first_name_line.setObjectName("first_name_line")
        self.authorGridLayout.addWidget(self.first_name_line, 2, 1, 1, 1)
        self.middle_name_label = QtWidgets.QLabel(self.AddBookPage)
        self.middle_name_label.setObjectName("middle_name_label")
        self.authorGridLayout.addWidget(self.middle_name_label, 3, 0, 1, 1)
        self.middle_name_line = QtWidgets.QLineEdit(self.AddBookPage)
        self.middle_name_line.setObjectName("middle_name_line")
        self.authorGridLayout.addWidget(self.middle_name_line, 3, 1, 1, 1)
        self.authorBarcodeverticalLayout.addLayout(self.authorGridLayout)
        spacerItem1 = QtWidgets.QSpacerItem(20, 128, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.authorBarcodeverticalLayout.addItem(spacerItem1)
        self.barcodeHorizontalLayout = QtWidgets.QHBoxLayout()
        self.barcodeHorizontalLayout.setObjectName("barcodeHorizontalLayout")
        self.barcode_label = QtWidgets.QLabel(self.AddBookPage)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.barcode_label.setFont(font)
        self.barcode_label.setObjectName("barcode_label")
        self.barcodeHorizontalLayout.addWidget(self.barcode_label)
        self.barcode_line = QtWidgets.QLineEdit(self.AddBookPage)
        self.barcode_line.setText("")
        self.barcode_line.setObjectName("barcode_line")
        self.barcodeHorizontalLayout.addWidget(self.barcode_line)
        self.authorBarcodeverticalLayout.addLayout(self.barcodeHorizontalLayout)
        spacerItem2 = QtWidgets.QSpacerItem(20, 68, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.authorBarcodeverticalLayout.addItem(spacerItem2)
        self.btnSplitterLayout = QtWidgets.QSplitter(self.AddBookPage)
        self.btnSplitterLayout.setOrientation(QtCore.Qt.Horizontal)
        self.btnSplitterLayout.setObjectName("btnSplitterLayout")
        self.add_book_cancel_btn = QtWidgets.QPushButton(self.btnSplitterLayout)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.add_book_cancel_btn.setFont(font)
        self.add_book_cancel_btn.setMouseTracking(True)
        self.add_book_cancel_btn.setAutoDefault(True)
        self.add_book_cancel_btn.setObjectName("add_book_cancel_btn")
        self.add_book_btn = QtWidgets.QPushButton(self.btnSplitterLayout)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.add_book_btn.setFont(font)
        self.add_book_btn.setMouseTracking(True)
        self.add_book_btn.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.add_book_btn.setAutoFillBackground(True)
        self.add_book_btn.setAutoDefault(True)
        self.add_book_btn.setObjectName("add_book_btn")
        self.authorBarcodeverticalLayout.addWidget(self.btnSplitterLayout)
        self.gridLayout_4.addLayout(self.authorBarcodeverticalLayout, 0, 2, 3, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 190, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_4.addItem(spacerItem3, 1, 0, 1, 1)
        self.bookGridLayout = QtWidgets.QGridLayout()
        self.bookGridLayout.setObjectName("bookGridLayout")
        self.book_label = QtWidgets.QLabel(self.AddBookPage)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.book_label.setFont(font)
        self.book_label.setObjectName("book_label")
        self.bookGridLayout.addWidget(self.book_label, 0, 0, 1, 1)
        self.book_title_label = QtWidgets.QLabel(self.AddBookPage)
        self.book_title_label.setObjectName("book_title_label")
        self.bookGridLayout.addWidget(self.book_title_label, 1, 0, 1, 1)
        self.book_title_line = QtWidgets.QLineEdit(self.AddBookPage)
        self.book_title_line.setObjectName("book_title_line")
        self.bookGridLayout.addWidget(self.book_title_line, 1, 1, 1, 1)
        self.isbn_label = QtWidgets.QLabel(self.AddBookPage)
        self.isbn_label.setObjectName("isbn_label")
        self.bookGridLayout.addWidget(self.isbn_label, 2, 0, 1, 1)
        self.isbn_line = QtWidgets.QLineEdit(self.AddBookPage)
        self.isbn_line.setObjectName("isbn_line")
        self.bookGridLayout.addWidget(self.isbn_line, 2, 1, 1, 1)
        self.language_label = QtWidgets.QLabel(self.AddBookPage)
        self.language_label.setObjectName("language_label")
        self.bookGridLayout.addWidget(self.language_label, 3, 0, 1, 1)
        self.language_box = QtWidgets.QComboBox(self.AddBookPage)
        self.language_box.setEnabled(True)
        self.language_box.setEditable(False)
        self.language_box.setInsertPolicy(QtWidgets.QComboBox.NoInsert)
        self.language_box.setMinimumContentsLength(0)
        self.language_box.setObjectName("language_box")
        self.language_box.addItem("")
        self.language_box.addItem("")
        self.language_box.addItem("")
        self.bookGridLayout.addWidget(self.language_box, 3, 1, 1, 1)
        self.pub_year_label = QtWidgets.QLabel(self.AddBookPage)
        self.pub_year_label.setObjectName("pub_year_label")
        self.bookGridLayout.addWidget(self.pub_year_label, 4, 0, 1, 1)
        self.pub_year_line = QtWidgets.QLineEdit(self.AddBookPage)
        self.pub_year_line.setObjectName("pub_year_line")
        self.bookGridLayout.addWidget(self.pub_year_line, 4, 1, 1, 1)
        self.genre_label = QtWidgets.QLabel(self.AddBookPage)
        self.genre_label.setObjectName("genre_label")
        self.bookGridLayout.addWidget(self.genre_label, 5, 0, 1, 1)
        self.genre_box = QtWidgets.QComboBox(self.AddBookPage)
        self.genre_box.setEnabled(True)
        self.genre_box.setEditable(False)
        self.genre_box.setInsertPolicy(QtWidgets.QComboBox.NoInsert)
        self.genre_box.setMinimumContentsLength(0)
        self.genre_box.setObjectName("genre_box")
        self.genre_box.addItem("")
        self.genre_box.addItem("")
        self.bookGridLayout.addWidget(self.genre_box, 5, 1, 1, 1)
        self.gridLayout_4.addLayout(self.bookGridLayout, 0, 0, 1, 1)
        self.seriesGridLayout = QtWidgets.QGridLayout()
        self.seriesGridLayout.setObjectName("seriesGridLayout")
        self.series_label = QtWidgets.QLabel(self.AddBookPage)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.series_label.setFont(font)
        self.series_label.setObjectName("series_label")
        self.seriesGridLayout.addWidget(self.series_label, 0, 0, 1, 1)
        self.series_title_label = QtWidgets.QLabel(self.AddBookPage)
        self.series_title_label.setObjectName("series_title_label")
        self.seriesGridLayout.addWidget(self.series_title_label, 1, 0, 1, 1)
        self.series_title_line = QtWidgets.QLineEdit(self.AddBookPage)
        self.series_title_line.setText("")
        self.series_title_line.setObjectName("series_title_line")
        self.seriesGridLayout.addWidget(self.series_title_line, 1, 1, 1, 1)
        self.in_series_label = QtWidgets.QLabel(self.AddBookPage)
        self.in_series_label.setObjectName("in_series_label")
        self.seriesGridLayout.addWidget(self.in_series_label, 2, 0, 1, 1)
        self.in_series_line = QtWidgets.QLineEdit(self.AddBookPage)
        self.in_series_line.setObjectName("in_series_line")
        self.seriesGridLayout.addWidget(self.in_series_line, 2, 1, 1, 1)
        self.gridLayout_4.addLayout(self.seriesGridLayout, 2, 0, 1, 1)
        StackedWidget.addWidget(self.AddBookPage)

        self.retranslateUi(StackedWidget)
        StackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(StackedWidget)
        StackedWidget.setTabOrder(self.user_line, self.pass_line)
        StackedWidget.setTabOrder(self.pass_line, self.loginBtn)
        StackedWidget.setTabOrder(self.loginBtn, self.book_title_line)
        StackedWidget.setTabOrder(self.book_title_line, self.isbn_line)
        StackedWidget.setTabOrder(self.isbn_line, self.language_box)
        StackedWidget.setTabOrder(self.language_box, self.pub_year_line)
        StackedWidget.setTabOrder(self.pub_year_line, self.genre_box)
        StackedWidget.setTabOrder(self.genre_box, self.series_title_line)
        StackedWidget.setTabOrder(self.series_title_line, self.in_series_line)
        StackedWidget.setTabOrder(self.in_series_line, self.last_name_line)
        StackedWidget.setTabOrder(self.last_name_line, self.first_name_line)
        StackedWidget.setTabOrder(self.first_name_line, self.middle_name_line)
        StackedWidget.setTabOrder(self.middle_name_line, self.barcode_line)
        StackedWidget.setTabOrder(self.barcode_line, self.add_book_btn)
        StackedWidget.setTabOrder(self.add_book_btn, self.add_book_cancel_btn)

    def retranslateUi(self, StackedWidget):
        _translate = QtCore.QCoreApplication.translate
        StackedWidget.setWindowTitle(_translate("StackedWidget", "FUBC Library"))
        self.user_label.setText(_translate("StackedWidget", "User Name"))
        self.pass_label.setText(_translate("StackedWidget", "Password"))
        self.loginBtn.setText(_translate("StackedWidget", "Login "))
        self.login_error_label.setText(_translate("StackedWidget", "<html><head/><body><p><span style=\" color:#ff0000;\">User Name or Password Incorrect! Please try again.</span></p></body></html>"))
        self.author_label.setText(_translate("StackedWidget", "Author"))
        self.last_label.setText(_translate("StackedWidget", "Last Name"))
        self.first_name_label.setText(_translate("StackedWidget", "First Name"))
        self.middle_name_label.setText(_translate("StackedWidget", "Middle Name"))
        self.barcode_label.setText(_translate("StackedWidget", "Barcode"))
        self.add_book_cancel_btn.setText(_translate("StackedWidget", "Clear"))
        self.add_book_btn.setText(_translate("StackedWidget", "Add Book"))
        self.book_label.setText(_translate("StackedWidget", "Book"))
        self.book_title_label.setText(_translate("StackedWidget", "Title "))
        self.isbn_label.setText(_translate("StackedWidget", "ISBN"))
        self.language_label.setText(_translate("StackedWidget", "Language"))
        self.language_box.setItemText(0, _translate("StackedWidget", "RU"))
        self.language_box.setItemText(1, _translate("StackedWidget", "UA"))
        self.language_box.setItemText(2, _translate("StackedWidget", "EN"))
        self.pub_year_label.setText(_translate("StackedWidget", "Publication Year"))
        self.genre_label.setText(_translate("StackedWidget", "Genre"))
        self.genre_box.setItemText(0, _translate("StackedWidget", "Християнські Романи"))
        self.genre_box.setItemText(1, _translate("StackedWidget", "Різні"))
        self.series_label.setText(_translate("StackedWidget", "Series"))
        self.series_title_label.setText(_translate("StackedWidget", "Series Title"))
        self.in_series_label.setText(_translate("StackedWidget", "In Series Number"))

