# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\fubc_lib.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_StackedWidget(object):
    def setupUi(self, StackedWidget):
        StackedWidget.setObjectName("StackedWidget")
        StackedWidget.resize(570, 415)
        StackedWidget.setStyleSheet("Fusion")
        self.LoginPage = QtWidgets.QWidget()
        self.LoginPage.setObjectName("LoginPage")
        self.formLayout_3 = QtWidgets.QFormLayout(self.LoginPage)
        self.formLayout_3.setContentsMargins(11, 300, -1, 11)
        self.formLayout_3.setObjectName("formLayout_3")
        self.formLayoutLabels = QtWidgets.QFormLayout()
        self.formLayoutLabels.setLabelAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.formLayoutLabels.setHorizontalSpacing(4)
        self.formLayoutLabels.setVerticalSpacing(2)
        self.formLayoutLabels.setObjectName("formLayoutLabels")
        self.user_label = QtWidgets.QLabel(self.LoginPage)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Black")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.user_label.setFont(font)
        self.user_label.setObjectName("user_label")
        self.formLayoutLabels.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.user_label)
        self.pass_label = QtWidgets.QLabel(self.LoginPage)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Black")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pass_label.setFont(font)
        self.pass_label.setIndent(12)
        self.pass_label.setOpenExternalLinks(False)
        self.pass_label.setObjectName("pass_label")
        self.formLayoutLabels.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.pass_label)
        self.formLayout_3.setLayout(0, QtWidgets.QFormLayout.LabelRole, self.formLayoutLabels)
        self.formLayoutLineEdit = QtWidgets.QFormLayout()
        self.formLayoutLineEdit.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.formLayoutLineEdit.setContentsMargins(-1, 6, -1, -1)
        self.formLayoutLineEdit.setObjectName("formLayoutLineEdit")
        self.user_line = QtWidgets.QLineEdit(self.LoginPage)
        self.user_line.setText("")
        self.user_line.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.user_line.setObjectName("user_line")
        self.formLayoutLineEdit.setWidget(0, QtWidgets.QFormLayout.SpanningRole, self.user_line)
        self.pass_line = QtWidgets.QLineEdit(self.LoginPage)
        self.pass_line.setText("")
        self.pass_line.setEchoMode(QtWidgets.QLineEdit.Password)
        self.pass_line.setObjectName("pass_line")
        self.formLayoutLineEdit.setWidget(1, QtWidgets.QFormLayout.SpanningRole, self.pass_line)
        self.formLayout_3.setLayout(0, QtWidgets.QFormLayout.FieldRole, self.formLayoutLineEdit)
        self.loginBtn = QtWidgets.QPushButton(self.LoginPage)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Black")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.loginBtn.setFont(font)
        self.loginBtn.setAutoDefault(True)
        self.loginBtn.setObjectName("loginBtn")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.loginBtn)
        StackedWidget.addWidget(self.LoginPage)
        self.AddBookPage = QtWidgets.QWidget()
        self.AddBookPage.setObjectName("AddBookPage")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.AddBookPage)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label = QtWidgets.QLabel(self.AddBookPage)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout_3.addWidget(self.label, 0, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.AddBookPage)
        self.label_6.setObjectName("label_6")
        self.gridLayout_3.addWidget(self.label_6, 1, 0, 1, 1)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.AddBookPage)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.gridLayout_3.addWidget(self.lineEdit_3, 1, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.AddBookPage)
        self.label_7.setObjectName("label_7")
        self.gridLayout_3.addWidget(self.label_7, 2, 0, 1, 1)
        self.lineEdit_4 = QtWidgets.QLineEdit(self.AddBookPage)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.gridLayout_3.addWidget(self.lineEdit_4, 2, 1, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.AddBookPage)
        self.label_8.setObjectName("label_8")
        self.gridLayout_3.addWidget(self.label_8, 3, 0, 1, 1)
        self.comboBox = QtWidgets.QComboBox(self.AddBookPage)
        self.comboBox.setEnabled(True)
        self.comboBox.setEditable(True)
        self.comboBox.setInsertPolicy(QtWidgets.QComboBox.NoInsert)
        self.comboBox.setMinimumContentsLength(0)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.gridLayout_3.addWidget(self.comboBox, 3, 1, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.AddBookPage)
        self.label_9.setObjectName("label_9")
        self.gridLayout_3.addWidget(self.label_9, 4, 0, 1, 1)
        self.lineEdit_5 = QtWidgets.QLineEdit(self.AddBookPage)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.gridLayout_3.addWidget(self.lineEdit_5, 4, 1, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.AddBookPage)
        self.label_12.setObjectName("label_12")
        self.gridLayout_3.addWidget(self.label_12, 5, 0, 1, 1)
        self.comboBox_2 = QtWidgets.QComboBox(self.AddBookPage)
        self.comboBox_2.setEnabled(True)
        self.comboBox_2.setEditable(True)
        self.comboBox_2.setInsertPolicy(QtWidgets.QComboBox.NoInsert)
        self.comboBox_2.setMinimumContentsLength(0)
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.gridLayout_3.addWidget(self.comboBox_2, 5, 1, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout_3, 0, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(55, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem, 0, 1, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_2 = QtWidgets.QLabel(self.AddBookPage)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 0, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.AddBookPage)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 1, 0, 1, 1)
        self.lineEdit_6 = QtWidgets.QLineEdit(self.AddBookPage)
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.gridLayout_2.addWidget(self.lineEdit_6, 1, 1, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.AddBookPage)
        self.label_10.setObjectName("label_10")
        self.gridLayout_2.addWidget(self.label_10, 2, 0, 1, 1)
        self.lineEdit_7 = QtWidgets.QLineEdit(self.AddBookPage)
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.gridLayout_2.addWidget(self.lineEdit_7, 2, 1, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.AddBookPage)
        self.label_11.setObjectName("label_11")
        self.gridLayout_2.addWidget(self.label_11, 3, 0, 1, 1)
        self.lineEdit_8 = QtWidgets.QLineEdit(self.AddBookPage)
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.gridLayout_2.addWidget(self.lineEdit_8, 3, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_2)
        spacerItem1 = QtWidgets.QSpacerItem(20, 128, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.series_label_2 = QtWidgets.QLabel(self.AddBookPage)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.series_label_2.setFont(font)
        self.series_label_2.setObjectName("series_label_2")
        self.horizontalLayout.addWidget(self.series_label_2)
        self.lineEdit_9 = QtWidgets.QLineEdit(self.AddBookPage)
        self.lineEdit_9.setText("")
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.horizontalLayout.addWidget(self.lineEdit_9)
        self.verticalLayout.addLayout(self.horizontalLayout)
        spacerItem2 = QtWidgets.QSpacerItem(20, 68, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem2)
        self.splitter = QtWidgets.QSplitter(self.AddBookPage)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.pushButton_2 = QtWidgets.QPushButton(self.splitter)
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton = QtWidgets.QPushButton(self.splitter)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout.addWidget(self.splitter)
        self.gridLayout_4.addLayout(self.verticalLayout, 0, 2, 3, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 127, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_4.addItem(spacerItem3, 1, 0, 1, 1)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.series_label = QtWidgets.QLabel(self.AddBookPage)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.series_label.setFont(font)
        self.series_label.setObjectName("series_label")
        self.gridLayout.addWidget(self.series_label, 0, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.AddBookPage)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 1, 0, 1, 1)
        self.lineEdit = QtWidgets.QLineEdit(self.AddBookPage)
        self.lineEdit.setText("")
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout.addWidget(self.lineEdit, 1, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.AddBookPage)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 2, 0, 1, 1)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.AddBookPage)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.gridLayout.addWidget(self.lineEdit_2, 2, 1, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout, 2, 0, 1, 1)
        StackedWidget.addWidget(self.AddBookPage)

        self.retranslateUi(StackedWidget)
        QtCore.QMetaObject.connectSlotsByName(StackedWidget)

    def retranslateUi(self, StackedWidget):
        _translate = QtCore.QCoreApplication.translate
        StackedWidget.setWindowTitle(_translate("StackedWidget", "FUBC Library"))
        self.user_label.setText(_translate("StackedWidget", "User Name"))
        self.pass_label.setText(_translate("StackedWidget", "Password"))
        self.loginBtn.setText(_translate("StackedWidget", "Log In "))
        self.label.setText(_translate("StackedWidget", "Book"))
        self.label_6.setText(_translate("StackedWidget", "Title "))
        self.label_7.setText(_translate("StackedWidget", "ISBN"))
        self.label_8.setText(_translate("StackedWidget", "Language"))
        self.comboBox.setItemText(0, _translate("StackedWidget", "RU"))
        self.comboBox.setItemText(1, _translate("StackedWidget", "UA"))
        self.comboBox.setItemText(2, _translate("StackedWidget", "EN"))
        self.label_9.setText(_translate("StackedWidget", "Publication Year"))
        self.label_12.setText(_translate("StackedWidget", "Genre"))
        self.comboBox_2.setItemText(0, _translate("StackedWidget", "Християнські Романи"))
        self.comboBox_2.setItemText(1, _translate("StackedWidget", "Різні"))
        self.label_2.setText(_translate("StackedWidget", "Author"))
        self.label_3.setText(_translate("StackedWidget", "Last Name"))
        self.label_10.setText(_translate("StackedWidget", "First Name"))
        self.label_11.setText(_translate("StackedWidget", "Middle Name"))
        self.series_label_2.setText(_translate("StackedWidget", "Barcode"))
        self.pushButton_2.setText(_translate("StackedWidget", "Cancel"))
        self.pushButton.setText(_translate("StackedWidget", "Add Book"))
        self.series_label.setText(_translate("StackedWidget", "Series"))
        self.label_4.setText(_translate("StackedWidget", "Series Title"))
        self.label_5.setText(_translate("StackedWidget", "In Series Number"))

